/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CampaignInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contributions"
      | "contributorsCount"
      | "createMilestone"
      | "creator"
      | "deadline"
      | "description"
      | "donate"
      | "fundingGoal"
      | "getMilestonesCount"
      | "getSummary"
      | "milestones"
      | "title"
      | "totalRaised"
      | "voteOnMilestone"
      | "withdrawMilestone"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Donated"
      | "MilestoneCreated"
      | "MilestoneVoted"
      | "MilestoneWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "donate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundingGoal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestonesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSummary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMilestone",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundingGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestonesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMilestone",
    data: BytesLike
  ): Result;
}

export namespace DonatedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [description: string, amount: BigNumberish];
  export type OutputTuple = [description: string, amount: bigint];
  export interface OutputObject {
    description: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneVotedEvent {
  export type InputTuple = [milestoneIndex: BigNumberish, voter: AddressLike];
  export type OutputTuple = [milestoneIndex: bigint, voter: string];
  export interface OutputObject {
    milestoneIndex: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneWithdrawnEvent {
  export type InputTuple = [milestoneIndex: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [milestoneIndex: bigint, amount: bigint];
  export interface OutputObject {
    milestoneIndex: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Campaign extends BaseContract {
  connect(runner?: ContractRunner | null): Campaign;
  waitForDeployment(): Promise<this>;

  interface: CampaignInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  contributorsCount: TypedContractMethod<[], [bigint], "view">;

  createMilestone: TypedContractMethod<
    [_description: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  creator: TypedContractMethod<[], [string], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  description: TypedContractMethod<[], [string], "view">;

  donate: TypedContractMethod<[], [void], "payable">;

  fundingGoal: TypedContractMethod<[], [bigint], "view">;

  getMilestonesCount: TypedContractMethod<[], [bigint], "view">;

  getSummary: TypedContractMethod<
    [],
    [[string, string, string, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        description: string;
        amount: bigint;
        approvalCount: bigint;
        isCompleted: boolean;
        isWithdrawn: boolean;
      }
    ],
    "view"
  >;

  title: TypedContractMethod<[], [string], "view">;

  totalRaised: TypedContractMethod<[], [bigint], "view">;

  voteOnMilestone: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawMilestone: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "contributorsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMilestone"
  ): TypedContractMethod<
    [_description: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundingGoal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMilestonesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [],
    [[string, string, string, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        description: string;
        amount: bigint;
        approvalCount: bigint;
        isCompleted: boolean;
        isWithdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "title"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteOnMilestone"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawMilestone"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Donated"
  ): TypedContractEvent<
    DonatedEvent.InputTuple,
    DonatedEvent.OutputTuple,
    DonatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneVoted"
  ): TypedContractEvent<
    MilestoneVotedEvent.InputTuple,
    MilestoneVotedEvent.OutputTuple,
    MilestoneVotedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneWithdrawn"
  ): TypedContractEvent<
    MilestoneWithdrawnEvent.InputTuple,
    MilestoneWithdrawnEvent.OutputTuple,
    MilestoneWithdrawnEvent.OutputObject
  >;

  filters: {
    "Donated(address,uint256)": TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;
    Donated: TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;

    "MilestoneCreated(string,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneVoted(uint256,address)": TypedContractEvent<
      MilestoneVotedEvent.InputTuple,
      MilestoneVotedEvent.OutputTuple,
      MilestoneVotedEvent.OutputObject
    >;
    MilestoneVoted: TypedContractEvent<
      MilestoneVotedEvent.InputTuple,
      MilestoneVotedEvent.OutputTuple,
      MilestoneVotedEvent.OutputObject
    >;

    "MilestoneWithdrawn(uint256,uint256)": TypedContractEvent<
      MilestoneWithdrawnEvent.InputTuple,
      MilestoneWithdrawnEvent.OutputTuple,
      MilestoneWithdrawnEvent.OutputObject
    >;
    MilestoneWithdrawn: TypedContractEvent<
      MilestoneWithdrawnEvent.InputTuple,
      MilestoneWithdrawnEvent.OutputTuple,
      MilestoneWithdrawnEvent.OutputObject
    >;
  };
}
